# Goal: to run continuous integration pipeline for this project
name: CI

on:
  push:

jobs:
  code-lint:
    uses: ./.github/workflows/lint_and_test.yml

  docker-build-and-push:
    needs: code-lint
    uses: ./.github/workflows/docker.yml