#  Goal: to build a CICD pipeline - demo
name: CICD Demo

on:
  workflow_dispatch:

jobs:
  #CI
  code:
    runs-on: ubuntu-latest
    steps:
      - name: clone the code
        uses: actions/checkout@v4
  build:
    needs: code
    runs-on: ubuntu-latest
    steps:
      - name: build the code with docker 
        uses:  docker/setup-buildx-action@v3

    
 # test:
  #CD
 # deploye:
  
