# Goal: to run continuous integration pipeline for this project
name: CI

on:
  push:

jobs:
  #code lint
  code-lint:
    uses: ./.github/workflows/lint_and_test.yml

  #build
  docker-build-and-push:
    needs: code-lint
    secrets: inherit
    uses: ./.github/workflows/docker.yml

  #deploy
  CD:
    needs: docker-build-and-push
    uses: ./.github/workflows/CD.yml
    secrets: inherit