# Goal: to scan dynamic running application DAST and security issues
name: DAST Scan
on:
    workflow_call:
jobs:
    dast-scan:
        runs-on: ubuntu-latest
        steps: 
             - name: code checkout
               uses: actions/checkout@v7
               
             - name: wait for server to be healthy
               run: |
                 echo "Waiting for the server to be healthy..."
                 timeout=60 sh -c 'until curl -s http://${{secrets.EC2_HOST}}:8080 > /dev/null; do sleep 5; done'

                #scan running application 
             - name: owasp zap baseline scan
               uses: zaproxy/action-baseline@v0.14.0
               with:
                 target: http://$((secrets.EC2_HOST)):80
                 fail_action: false
                 allow_issue_writing: false