#Goal: call workflows in order to implement shift left security in the CICD pipeline
name: DevSecOps Pipeline
on:
    push:

jobs:
     #CI

  #secrete scanning
    secrets-scanning:
      uses: ./.github/workflows/secrets-scanning.yml
      secrets: inherit

  #code lint and test
    code-lint:
      uses: ./.github/workflows/lint_and_test.yml
      needs: secrets-scanning
      

  #build
  #  docker-build-and-push:
  #    needs: code-lint
  #    secrets: inherit
  #    uses: ./.github/workflows/docker.yml

  #CD  
  #deploy
  #  CD:
   #   needs: docker-build-and-push
    #  uses: ./.github/workflows/CD.yml
     # secrets: inherit
    

