#Goal: call workflows in order to implement shift left security in the CICD pipeline
name: DevSecOps Pipeline
on:
    push:

jobs:
     #CI

  #secrete scanning
    secrets-scanning:
      uses: ./.github/workflows/secrets-scanning.yml
      secrets: inherit

  #code lint and test
    code-lint:
      uses: ./.github/workflows/lint_and_test.yml
      needs: secrets-scanning

  #sonar scan SAAST
    sonar-scan:
      uses: ./.github/workflows/sonar-scan.yml
      needs: code-lint
      secrets: inherit
     
  #Dependency scan
    dependency-scan:
      uses: ./.github/workflows/Dependency-scan.yml
      needs: sonar-scan
  

  #build
    docker-build-and-scan:
      needs: dependency-scan
      uses: ./.github/workflows/trivy-scan.yml
      secrets: inherit

#push the docker image to docker hub
    docker-push:
      needs: docker-build-and-scan
      uses: ./.github/workflows/docker-push.yml
      secrets: inherit

  #CD  
  #deploy
    CD:
      needs: docker-push
      uses: ./.github/workflows/CD.yml
      secrets: inherit
    
#DAST (SHIFT RIGHT SECURITY)
    DAST:
      needs: CD
      uses: ./.github/workflows/dast.yml
      secrets: inherit

