# Goal: to scan the code for any secrets tokens, API keys, or any leaks
#if find we can rotate the exposed secrets and update the secrets in github repository settings
name: Secrets Scanning
on:
    workflow_call:

jobs:
    secrets-scanning:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout code
          uses: actions/checkout@v7  # clone the code to the runner
          with:
            fetch-depth: 0 # froom the very first commit to the latest commit, pull all the code to scan for any secrets tokens, API keys, or any leaks

        - name: scan for leaks
          uses: gitleaks/gitleaks-action@v3 # scan the code for any secrets tokens, API keys, or any leaks
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
           # license Only required for Organizations, not personal accounts.
           # GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_LICENSE }} 